New subnet create ux
ava-labs/avalanche-cli pull request #2027
Opened 2024-07-12 20:25 UTC by felipemadero

Closes https://github.com/ava-labs/avalanche-cli/issues/1917

2024-07-23 17:23 UTC, felipemadero commented on cmd/subnetcmd/create.go
>  }
here https://github.com/ava-labs/avalanche-cli/pull/2048

2024-07-23 17:23 UTC, felipemadero commented on pkg/vm/evmPrompts.go
> +			continue
here https://github.com/ava-labs/avalanche-cli/pull/2050

2024-07-24 21:42 UTC, martineckardt requested changes

2024-07-24 21:42 UTC, martineckardt commented on cmd/subnetcmd/upgradecmd/generate.go
> +	burnPrompt := "Should fees be burnt?"
```suggestion
	burnPrompt := "By default, all transaction fees on Avalanche are burned (sent to a blackhole address). (Reward Manager Precompile)"
```

Answer options:
"I am fine with transaction fees being burned (Reward Manager Precompile OFF)"
"I want to customize the transaction fee distribution (Reward Manager Precompile ON)"

2024-07-24 21:42 UTC, martineckardt commented on pkg/teleporter/teleporter.go
> +	TeleporterPrefundedAddressBalance = big.NewInt(0).Mul(big.NewInt(1e18), big.NewInt(600))
Rename teleporter to InterchainMessaging. Also specify what this address is for (deployer)

2024-07-24 21:42 UTC, martineckardt commented on pkg/vm/allocations.go
> +func addTeleporterAllocation(
Rename to InterchainMessaging

2024-07-25 16:16 UTC, felipemadero commented on pkg/vm/evmPrompts.go
> +			ux.Logger.PrintToUser("Each blockchain on Avalanche has its own transaction fee token. To issue transactions users don't need to acquire ETH or AVAX and therefore the transaction fees are complete
nop. this is not the case here. it is the subnet evm native token that any subnet evm has. for c-chain is avax, and so on.

2024-07-25 17:17 UTC, merged